const express = require('express');
const router = express.Router();
const ProductController = require('../Controllers/products.controller');
router.get('/product', ProductController.getDocuments);
router.get('/product/phone', ProductController.getPhone);
router.get('/product/laptop', ProductController.getLaptop);
router.get('/product/accessory', ProductController.getAccessory);
router.get('/product/pc', ProductController.getPC);
router.get('/product/:name', ProductController.getSearch);
router.post('/add', ProductController.addProduct);
module.exports = router;
