POST  http://localhost:8080/api/register
Content-Type: application/json

{
    "name":"admin",
    "email":"admin@gmail.com",
    "password": "1234",
    "address":"Nam Dinh",
    "phone":"0969938892"
}
###

POST http://localhost:8080/api/login
Content-Type: application/json

{
    "email": "admin@gmail.com",
    "password": "1234"
}
###

DELETE  http://localhost:8080/api/delete
Content-Type: application/json

{
    "id":"63dd3c66794001e38e12b891"
   
}
###

POST http://localhost:8080/api/add
Content-Type: application/json

{
    "name":"Bộ Vali Phụ kiện cho Asus" ,
    "img": "https://cdn2.cellphones.com.vn/358x358,webp,q100/media/catalog/product/i/r/irhqclp.jpg",
    "price":"12000000" ,
    "descreption": "Đây là cái điện thoại oppo",
    "trademark": "dell",
    "origin":"trung quốc",
    "category":"Điện thoại"
}
###

POST http://localhost:8080/api/search/iphone
Content-Type: application/json

{
    "name":"oppo" ,
}

###

GET http://localhost:8080/api/product/getid/63efde8192fc69f4a75e12cd
Content-Type: application/json

{
    
}